apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-configs
parameters:
  - name: NAME
    displayName: null
    description: 'the module name entered when run yo bcdk:pipeline, which is zeva'
    value: zeva
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97
    value: ''
    required: true
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: 'Environment name, dev, test and prod'
    required: true
  - name: HOST_NAME
    displayName: Host name for route
    description: Host name for route
    required: true
  - name: BACKEND_HOST_NAME
    displayName: The backend host name
    description: 'The backend host name'
    required: true
  - name: SSO_NAME
    displayName: SSO Name
    description: values include dev.oidc.gov.bc.ca, test.oidc.gov.bc.ca and oidc.gov.bc.ca
    required: true
  - name: KEYCLOAK_REALM
    value: rzh2zkjq
    displayName: keycload realm name
    description: keycload realm name, value is rzh2zkjq
    required: true
  - name: DJANGO_DEBUG
    value: 'False'
    displayName: django debug value
    description: django debug value
    required: true    
  - name: OCP_NAME
    displayName: Openshift Cluster Name
    description: Openshift Cluster Name
    required: true     
  - name: LOGOUT_HOST
    displayName: the logout host
    description: the logout host
    required: true     
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: ${NAME}-config${SUFFIX}
    data:
      apibase: https://${BACKEND_HOST_NAME}/api/
      database_engine: postgresql
      database_name: zeva
      database_service_name: patroni-master${SUFFIX}
      django_debug: ${DJANGO_DEBUG}
      email_from_address: donotreply@gov.bc.ca
      email_sending_enabled: 'False'
      env_name: ${ENV_NAME}
      keycloak_audience: zeva
      keycloak_authority: https://${SSO_NAME}/auth/realms/${KEYCLOAK_REALM}
      keycloak_certs_url: https://${SSO_NAME}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      keycloak_client_id: zeva
      keycloak_issuer: https://${SSO_NAME}/auth/realms/${KEYCLOAK_REALM}
      keycloak_logout_redirect_url: https://${LOGOUT_HOST}/clp-cgi/logoff.cgi?returl=https://${HOST_NAME}&retnow=1
      keycloak_realm_name: ${KEYCLOAK_REALM}
      keycloak_realm_url: https://${SSO_NAME}/auth/realms/${KEYCLOAK_REALM}
      keycloak_realm: https://${SSO_NAME}/auth/realms/${KEYCLOAK_REALM}
      keycloak_sa_baseurl: https://${SSO_NAME}
      keycloak_sa_client_id: zeva-django-sa
      keycloak_sa_realm: ${KEYCLOAK_REALM}
      keycloak_url: https://${SSO_NAME}/auth
      minio_endpoint: zeva-minio-${ENV_NAME}.${OCP_NAME}.gov.bc.ca
      postgresql_service_host: patroni-master${SUFFIX}.tbiwaq-${ENV_NAME}.svc.cluster.local
      postgresql_service_port: '5432'
      rabbitmq_enabled: 'False'
      rabbitmq_host: ${NAME}${SUFFIX}-rabbitmq-cluster.tbiwaq-${ENV_NAME}.svc.cluster.local
      rabbitmq_port: '5672'
      rabbitmq_vhost: /zeva
