apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-configmap
parameters:
  - name: ENV_NAME
    displayName: SSO Name
    description: values include dev, test and prod
    required: true
  - name: SSO_NAME
    displayName: SSO Name
    description: values include sso-dev, sso-test and sso
    required: true
  - name: KEYCLOAK_REALM
    displayName: keycload realm name
    description: keycload realm name, value is rzh2zkjq
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: zeva-config
    data:
      database_name: zeva
      database_engine: postgresql
      database_service_name: postgresql
      postgresql_service_host: postgresql.tbiwaq-${ENV_NAME}.svc.cluster.local
      postgresql_service_port: '5432'
      keycloak_certs_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      keycloak_realm: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_realm_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_authority: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_issuer: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_audience: zeva
      keycloak_client_id: zeva
      keycloak_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth
      keycloak_sa_baseurl: https://${SSO_NAME}.pathfinder.gov.bc.ca
      keycloak_sa_client_id: zeva-django-sa
      keycloak_sa_realm: ${KEYCLOAK_REALM}
      django_debug: 'False'
      apibase: http://envoy.tbiwaq-${ENV_NAME}.svc.cluster.local:10000/api
      rabbitmq_enabled: 'false'
      rabbitmq_vhost: /zeva
      rabbitmq_user: zeva
      rabbitmq_host: rabbitmq.tbiwaq-${ENV_NAME}.svc.cluster.local
      rabbitmq_port: '5672'
      smtp_server_host: apps.smtp.gov.bc.ca
      smtp_server_port: '25'
      email_sending_enabled: 'false'
      email_from_address: donotreply@gov.bc.ca
