name: PR Build

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  loginopenshift:
    name: login Opneshift
    runs-on: ubuntu-16.04
    env:
      BUILD_ID: ${{ github.event.number }}
    steps:
      - name: Login to Openshift
        run: oc login --token=${{ secrets.TOOLS_SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443

      - name: Run oc command to list projects
        run: oc projects

      - name: Checkout Target Branch
        uses: actions/checkout@v2

      - name: Run Build
        run: npm run build -- --pr=$BUILD_ID --env=build
